# Generated by Django 3.2.19 on 2023-06-10 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_imge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imge',
            new_name='img',
        ),
    ]
